### ISSUE TITLE
Truffle Support

### ISSUE THREAD

**Issue by ylluminate** [ankane/tensorflow#2]
Nice and exciting work!  You might want to both collaborate with Truffle and chime in here:
https://github.com/oracle/truffleruby/issues/1424

I'm pretty certain that if there are any problems on the C front they'll help with `sulong` issues.

**Comment by ankane** [comment]
Hey @ylluminate, thanks for the suggestion 👍 This isn't going to be a priority for the project, but please keep the community updated if you get it working.
