### ISSUE TITLE
NoMethodError: undefined method `TFE_Execute' for TensorFlow::FFI:Module

### ISSUE THREAD

**Issue by kojix2** [ankane/tensorflow#7]
### Errors
```
FFI::NotFoundError: Function 'TFE_OpAddInputList' not found in [libtensorflow.so]
```
```
NoMethodError: undefined method `TFE_Execute' for TensorFlow::FFI:Module
Did you mean?  TFE_OpGetDevice
```

### Solved
Upgrading Tensorflow to 1.14.0
Tensorflow's Chinese, Japanese and Korean official pages are old.
If you see a link for version 1.13.1, you should go to the English page and download the latest version.

**Comment by ankane** [comment]
Thanks for following up with the solution @kojix2!
